plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${fabric_loom_version}"
    id 'checkstyle'
}

version = rootProject.version
group = rootProject.group

base {
    archivesName = archives_base_name
}

loom {
    splitEnvironmentSourceSets()
    accessWidenerPath = file('src/main/resources/dairatz.accesswidener')

    mods {
        dairatz {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

sourceSets {
    main {
        java.srcDir rootProject.file('common/src/main/java')
        resources.srcDir rootProject.file('common/src/main/resources')
    }
    client {
        java.srcDir rootProject.file('common/src/client/java')
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
}

checkstyle {
    toolVersion = '10.21.4'
    configFile = rootProject.file('config/checkstyle/checkstyle.xml')
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named('jar') {
    archiveVersion = "${project.version}+mc${minecraft_version}-fabric"
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_id}" }
    }
}

tasks.named('remapJar') {
    archiveVersion = "${project.version}+mc${minecraft_version}-fabric"
}

tasks.register('stageArtifact', Sync) {
    group = 'build'
    dependsOn tasks.named('remapJar')
    from(tasks.named('remapJar').flatMap { it.archiveFile })
    into(rootProject.layout.buildDirectory.dir('ci/1.21.11-fabric'))
}
