pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'dairatz'

def targetProjects = [
        '1.21.11-fabric'  : 'fabric',
        '1.21.11-forge'   : 'forge',
        '1.21.11-neoforge': 'neoforge'
]
def requestedTarget = gradle.startParameter.projectProperties['target']

if (requestedTarget != null && targetProjects.containsKey(requestedTarget)) {
    include targetProjects[requestedTarget]
} else {
    include targetProjects.values() as String[]
}
